/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class MatchingEngineTest {
    private final MatchingEngine engine = new MatchingEngine();

    MatchingEngineTest() {
        // TODO: Load test data
    }

    @Test
    void testTest() {
        assertTrue(engine.match(null, null) == null, "Testing the test setup");
    }
}
