/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Scanner;
import java.util.ArrayList;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;


class MatchingEngineTest {
    private final MatchingEngine engine = new MatchingEngine();
    private Scholarship[] scholarships;
    private Applicant[] applicants;

    MatchingEngineTest() throws Exception {
        scholarships = new Scholarship[44];
        applicants = new Applicant[25];

        SimpleDateFormat df = new SimpleDateFormat("MM-dd-yyyy");

        try {
            File file = new File("../../resources/ScholarshipTest.csv");
            Scanner scnr = new Scanner(file);
            String tempLine =  scnr.nextLine();
            int i = 0;

            while (scnr.hasNextLine()) {
                tempLine = scnr.nextLine();
                String[] inputs = tempLine.split(",");

                scholarships[i].setGPA(Double.parseDouble(inputs[1]));
                scholarships[i].setMajor(inputs[2]);
                scholarships[i].setMinor(inputs[3]);
                scholarships[i].setTransfer(Boolean.parseBoolean(inputs[4]));
                scholarships[i].setExpGradDate(df.parse(inputs[5]));
                scholarships[i].setAcademicYear(inputs[6]);
                scholarships[i].setEnrolledUnits(Integer.parseInt(inputs[7]));
                scholarships[i].setGender(inputs[8]);
                scholarships[i].setUSCitizenship(Boolean.parseBoolean(inputs[9]));
                scholarships[i].setScholarshipName(inputs[10]);
                scholarships[i].setDeadline(df.parse(inputs[12]));

                ++i;
            }

            scnr.close();

        }
        catch (FileNotFoundException excpt) {
            System.out.println("Error: Scholarship File Not Found");
        }

        try {
            File file = new File("../../resources/StudentTest.csv");
            Scanner scnr = new Scanner(file);
            String tempLine = scnr.nextLine();
            int i = 0;

            while (scnr.hasNextLine()) {
                tempLine = scnr.nextLine();
                String[] inputs = tempLine.split(",");

                applicants[i].setUSCitizenship(Boolean.parseBoolean(inputs[0]));
                applicants[i].setGender(inputs[1]);
                applicants[i].setStatement(inputs[2]);
                applicants[i].setStudentID(inputs[3]);
                applicants[i].setGPA(Double.parseDouble(inputs[5]));
                applicants[i].setMajors(new String[]{inputs[6]});
                applicants[i].setMinors(new String[]{inputs[7]});
                applicants[i].setTransfer(Boolean.parseBoolean(inputs[8]));
                applicants[i].setExpGradDate(df.parse(inputs[9]));
                applicants[i].setAcademicYear(inputs[10]);
                applicants[i].setEnrolledUnits(Integer.parseInt(inputs[11]));

                ++i;
            }

            scnr.close();
        }
        catch (FileNotFoundException excpt) {
            System.out.println("Error Student File Not Found");
        }
    }

    @Test
    void testTest() {
        assertTrue(engine.match(null, null) == null, "Testing the test setup");

        System.out.println("Testing matching");
        try {
            File file = new File("../../resources/expectedMatching.csv");
            Scanner scnr = new Scanner(file);
            
            for (int i = 0; i < applicants.length; ++i) {
                ArrayList<Scholarship> matches = engine.match(applicants[i], scholarships);
                String temp = scnr.nextLine();
                String[] expectedMatches = temp.split(",");

                for (int j = 1; j < expectedMatches.length; ++j) {
                    if (matches.get(j - 1).getScholarshipName() != expectedMatches[j]) {
                        System.out.println("Applicant: " + applicants[i].getStudentID() + "failed to match with Scholarship: " + expectedMatches[j]);
                    }
                }
            }

            scnr.close();
        }
        catch (FileNotFoundException excpt) {
            System.out.println("Expected Matching File Not Found");
        }
    }
}
